### ISSUE TITLE
In footer, the unwanted content in uppercase can be removed, in privacy policy in the footer.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Aryanna-s-Coffee--Internal--June-20th#1]
**Actual result:**
In footer, the unwanted content in uppercase can be removed, in privacy policy in the footer.
https://www.awesomescreenshot.com/video/9658294?key=7ae56cc9dcb78b78c46f404ea630136b
**Expected result:**
The uppercase text content can be removed, it will be much better.

**Comment by stores-cedcommerce** [comment]
Done

**Comment by sudhanshu0603** [comment]
ok, resolved
