### ISSUE TITLE
Login page on the header.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Aryanna-s-Coffee--Internal--June-20th#10]
**Actual result:**
After typing the wrong input fields when we delete the input field data, then the error message is not disappearing.
![image](https://user-images.githubusercontent.com/102131636/175864445-798cf7a9-6247-417f-9a92-6420b6c0115e.png)

**Expected result:**
The error message have to be deleted.

**Comment by devSuneel** [comment]
resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
