### ISSUE TITLE
In homepage, the products are missing in the new arrivals section in above the footer.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Aryanna-s-Coffee--Internal--June-20th#16]
**Actual result:**
In homepage, the products are missing in the new arrivals section in above the footer.
![image](https://user-images.githubusercontent.com/102131636/175873132-332a65c7-3b1b-4461-a6ff-951f062531ac.png)

**Expected result:**
The product must be added in the new arrivals section above the footer.

**Comment by devSuneel** [comment]
resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
