### ISSUE TITLE
In cart page, the added product images have to be clickable in the cart page.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Aryanna-s-Coffee--Internal--June-20th#19]
**Actual result:**
In cart page, the added product images have to be clickable in the cart page.
![image](https://user-images.githubusercontent.com/102131636/175879703-f1992488-6664-4867-9cae-5df2f765ccb7.png)

**Expected result:**
The main image have to be clickable.

**Comment by devSuneel** [comment]
resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
