### ISSUE TITLE
In footer, return and refund policy the email is not clickable.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Aryanna-s-Coffee--Internal--June-20th#2]
**Actual result:**
In footer, return and refund policy the email is not clickable.
https://aryannascoffee.com/pages/returns-refund-policy
![image](https://user-images.githubusercontent.com/102131636/175858484-73140330-1623-465d-9caa-06f77e4b417b.png)

**Expected result:**
The email have to be clickable.

**Comment by devSuneel** [comment]
resolved
