### ISSUE TITLE
The last date needs to be updated.( Privacy policy)

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Aryanna-s-Coffee--Internal--June-20th#20]
https://aryannascoffee.com/pages/privacy-policy
**Actual result:**
The last date needs to be updated.( Privacy policy)
![image](https://user-images.githubusercontent.com/102131636/175883904-682bee54-9651-4171-ae34-7cdec9f4617e.png)
**Expected result:**
The last date must be updated in the privacy policy page.

**Comment by stores-cedcommerce** [comment]
Done

**Comment by sudhanshu0603** [comment]
ok, resolved
