### ISSUE TITLE
In cart page, the main image product which is added is not clickable.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Aryanna-s-Coffee--Internal--June-20th#26]
**Actual result:**
In cart page, the main image product which is added is not clickable.
![image](https://user-images.githubusercontent.com/102131636/175900973-39be29cc-8755-437a-b4bb-1cba17835a41.png)
**Expected result:**
The main image in the cart page, have to be clickable.

**Comment by devSuneel** [comment]
resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
