### ISSUE TITLE
About us content in the footer, the unwanted symbols are used along with the text content.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Aryanna-s-Coffee--Internal--June-20th#7]
**Actual result:**
About us content in the footer, the unwanted symbols are used along with the text content.
![image](https://user-images.githubusercontent.com/102131636/175861721-d39f3074-0189-4ca1-9b46-d78dfc135fea.png)

**Expected result:**
The extra unwanted symbol and content can be updated.

**Comment by stores-cedcommerce** [comment]
Done

**Comment by sudhanshu0603** [comment]
ok, resolved
