### ISSUE TITLE
When we select the option Skin care in the Appliances in the header then the handle is coming.(URL )

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Aryanna-s-Coffee--Internal--June-20th#9]
**Actual result:**
When we select the option Skin care in the Appliances in the header then the handle is coming.(URL )
https://aryannascoffee.com/collections/skin-care-1
https://aryannascoffee.com/collections/assorted-coffee-1
**Expected result:**
The handle must be removed from the url for the skin care.

**Comment by devSuneel** [comment]
resolved
